--------------------------------------------------------
--  Fichier créé - jeudi-janvier-07-2021   
--------------------------------------------------------
DROP TABLE "HACHEM"."ACHAT";
DROP TABLE "HACHEM"."CARTE_FIDELITE";
DROP TABLE "HACHEM"."CLIENT";
DROP TABLE "HACHEM"."COMPOSITION";
DROP TABLE "HACHEM"."CONGE";
DROP TABLE "HACHEM"."EMPLOYE";
DROP TABLE "HACHEM"."FOURNISSEUR";
DROP TABLE "HACHEM"."LIVRAISON";
DROP TABLE "HACHEM"."MACHINE";
DROP TABLE "HACHEM"."MP";
DROP TABLE "HACHEM"."PRODUIT";
DROP TABLE "HACHEM"."RECLAMATION";
DROP TABLE "HACHEM"."VENTE";
--------------------------------------------------------
--  DDL for Table ACHAT
--------------------------------------------------------

  CREATE TABLE "HACHEM"."ACHAT" 
   (	"NUM_COMMANDE" NUMBER, 
	"QUANTITE" NUMBER, 
	"PRIX" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"FOURNISSEUR" VARCHAR2(20 BYTE), 
	"DATE_ACHAT" VARCHAR2(20 BYTE), 
	"PRODUIT" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CARTE_FIDELITE
--------------------------------------------------------

  CREATE TABLE "HACHEM"."CARTE_FIDELITE" 
   (	"NUM_CARTE" NUMBER, 
	"DATE_DE_CREATION" VARCHAR2(20 BYTE), 
	"POINTS" NUMBER, 
	"TOTAL_ACHATS" NUMBER, 
	"STATUT" VARCHAR2(20 BYTE), 
	"REMISE" NUMBER, 
	"MATRICULE_FISCALE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "HACHEM"."CLIENT" 
   (	"NOM_ENTREPRISE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"MATRICULE_FISCALE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(100 BYTE), 
	"VILLE" VARCHAR2(50 BYTE), 
	"CODE_POSTAL" NUMBER, 
	"TEL" VARCHAR2(8 BYTE), 
	"FAX" VARCHAR2(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPOSITION
--------------------------------------------------------

  CREATE TABLE "HACHEM"."COMPOSITION" 
   (	"REF_PRODUIT" VARCHAR2(20 BYTE), 
	"REF_MP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGE
--------------------------------------------------------

  CREATE TABLE "HACHEM"."CONGE" 
   (	"ID_CONGE" NUMBER, 
	"ID" NUMBER, 
	"DATE_DEBUT" VARCHAR2(20 BYTE), 
	"DATE_FIN" VARCHAR2(20 BYTE), 
	"MOTIF" VARCHAR2(20 BYTE), 
	"TYPE_CONGE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "HACHEM"."EMPLOYE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"COURRIEL" VARCHAR2(30 BYTE), 
	"NUM_TEL" NUMBER, 
	"DATE_N" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(30 BYTE), 
	"FONCTION" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER, 
	"ETAT_CIVIL" VARCHAR2(20 BYTE), 
	"NATIONALITE" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "HACHEM"."FOURNISSEUR" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"NUMERO" NUMBER, 
	"RIB" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRODUIT" VARCHAR2(20 BYTE), 
	"DATE_AJOUT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRAISON
--------------------------------------------------------

  CREATE TABLE "HACHEM"."LIVRAISON" 
   (	"NUM_COM" VARCHAR2(20 BYTE), 
	"PRODUIT" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE), 
	"LIVREUR" VARCHAR2(20 BYTE), 
	"TOTAL" VARCHAR2(20 BYTE), 
	"DATE_ARRIVEE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MACHINE
--------------------------------------------------------

  CREATE TABLE "HACHEM"."MACHINE" 
   (	"CODE" VARCHAR2(20 BYTE) DEFAULT (null), 
	"DATEM" VARCHAR2(20 BYTE), 
	"FONCTIONNEMENT" VARCHAR2(20 BYTE), 
	"PUISSANCE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MP
--------------------------------------------------------

  CREATE TABLE "HACHEM"."MP" 
   (	"REFERENCE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"PRIX" NUMBER, 
	"DATE_ACHAT" VARCHAR2(25 BYTE), 
	"POIDS" NUMBER, 
	"VOLUME" NUMBER, 
	"COMMENTAIRE" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "HACHEM"."PRODUIT" 
   (	"CATEGORIE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"REFERENCE" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"DATE_DE_CREATION" VARCHAR2(20 BYTE), 
	"DATE_D_EXPIRATION" VARCHAR2(20 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"DIMENSIONS" NUMBER, 
	"POIDS" NUMBER, 
	"VOLUME" NUMBER, 
	"COMMENTAIRE" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "HACHEM"."RECLAMATION" 
   (	"CODEM" VARCHAR2(20 BYTE), 
	"CAUSE_PANNE" VARCHAR2(20 BYTE), 
	"DATE_PANNE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VENTE
--------------------------------------------------------

  CREATE TABLE "HACHEM"."VENTE" 
   (	"NUM_VENTE" VARCHAR2(20 BYTE), 
	"PROD" VARCHAR2(20 BYTE), 
	"QUANT" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"TOT" VARCHAR2(20 BYTE), 
	"DATE_ARR" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HACHEM.ACHAT
SET DEFINE OFF;
Insert into HACHEM.ACHAT (NUM_COMMANDE,QUANTITE,PRIX,DESCRIPTION,FOURNISSEUR,DATE_ACHAT,PRODUIT,NOM) values ('0','0',null,null,'123489','01/01/2000','Gel',null);
Insert into HACHEM.ACHAT (NUM_COMMANDE,QUANTITE,PRIX,DESCRIPTION,FOURNISSEUR,DATE_ACHAT,PRODUIT,NOM) values ('15','500',null,'ghhj','aaa123','01/01/2000','Gel',null);
REM INSERTING into HACHEM.CARTE_FIDELITE
SET DEFINE OFF;
REM INSERTING into HACHEM.CLIENT
SET DEFINE OFF;
Insert into HACHEM.CLIENT (NOM_ENTREPRISE,DESCRIPTION,MATRICULE_FISCALE,EMAIL,ADRESSE,VILLE,CODE_POSTAL,TEL,FAX) values ('hghg','fdf','ghghf','fdfd','dfdf','cvd','5','25252454','45442121');
Insert into HACHEM.CLIENT (NOM_ENTREPRISE,DESCRIPTION,MATRICULE_FISCALE,EMAIL,ADRESSE,VILLE,CODE_POSTAL,TEL,FAX) values ('hghg','fdf','fdfdfd','fdfd','dfdf','cvd','5','25252454','45442121');
REM INSERTING into HACHEM.COMPOSITION
SET DEFINE OFF;
Insert into HACHEM.COMPOSITION (REF_PRODUIT,REF_MP) values ('7','100');
Insert into HACHEM.COMPOSITION (REF_PRODUIT,REF_MP) values ('7','dfsfs');
Insert into HACHEM.COMPOSITION (REF_PRODUIT,REF_MP) values ('7','mah');
Insert into HACHEM.COMPOSITION (REF_PRODUIT,REF_MP) values ('8','77');
REM INSERTING into HACHEM.CONGE
SET DEFINE OFF;
Insert into HACHEM.CONGE (ID_CONGE,ID,DATE_DEBUT,DATE_FIN,MOTIF,TYPE_CONGE) values ('6164316','16495','01/01/2000','06/01/2000','fyjh,','Annuel');
Insert into HACHEM.CONGE (ID_CONGE,ID,DATE_DEBUT,DATE_FIN,MOTIF,TYPE_CONGE) values ('49316','946316','01/01/2000','06/01/2000','person','Annuel');
Insert into HACHEM.CONGE (ID_CONGE,ID,DATE_DEBUT,DATE_FIN,MOTIF,TYPE_CONGE) values ('43134','946316','04/01/2000','15/01/2000','cvbn,','Maternite');
REM INSERTING into HACHEM.EMPLOYE
SET DEFINE OFF;
Insert into HACHEM.EMPLOYE (ID,NOM,PRENOM,COURRIEL,NUM_TEL,DATE_N,ADRESSE,FONCTION,SALAIRE,ETAT_CIVIL,NATIONALITE,MDP) values ('16495','antar','HACHEM','HACHEM.antar@esprit.tn','55635214','10/01/2000','avenue hedi chaker','secretaire','300','Celibataire','tunisienne',null);
Insert into HACHEM.EMPLOYE (ID,NOM,PRENOM,COURRIEL,NUM_TEL,DATE_N,ADRESSE,FONCTION,SALAIRE,ETAT_CIVIL,NATIONALITE,MDP) values ('30000000','hhhh','lol','dfjgh@hjk.com','24315897','05/01/1994','jjjj','Ouvrier','300','Divorce(e)','France',null);
Insert into HACHEM.EMPLOYE (ID,NOM,PRENOM,COURRIEL,NUM_TEL,DATE_N,ADRESSE,FONCTION,SALAIRE,ETAT_CIVIL,NATIONALITE,MDP) values ('946316','karoui','cy','sirine@esprit.tn','97842156','08/01/2000','avenue','sect','100','Celibataire','tunisienne',null);
Insert into HACHEM.EMPLOYE (ID,NOM,PRENOM,COURRIEL,NUM_TEL,DATE_N,ADRESSE,FONCTION,SALAIRE,ETAT_CIVIL,NATIONALITE,MDP) values ('16431','med','mohamed','mohamed@esprit.tn','26493164','01/01/1994','mmm','Livreur','100','Celibataire','Tunisie',null);
REM INSERTING into HACHEM.FOURNISSEUR
SET DEFINE OFF;
Insert into HACHEM.FOURNISSEUR (MATRICULE,ADRESSE,NUMERO,RIB,NOM,PRODUIT,DATE_AJOUT) values ('1425',null,'0','0','test123','gel','01/01/2000');
Insert into HACHEM.FOURNISSEUR (MATRICULE,ADRESSE,NUMERO,RIB,NOM,PRODUIT,DATE_AJOUT) values ('123489',null,'0','0','HACHEM','gel','01/01/2000');
Insert into HACHEM.FOURNISSEUR (MATRICULE,ADRESSE,NUMERO,RIB,NOM,PRODUIT,DATE_AJOUT) values ('dddd2',null,'0','0','hhhhh','gel','01/01/2000');
Insert into HACHEM.FOURNISSEUR (MATRICULE,ADRESSE,NUMERO,RIB,NOM,PRODUIT,DATE_AJOUT) values ('dddd1',null,'0','0','aaaa','gel','01/01/2000');
Insert into HACHEM.FOURNISSEUR (MATRICULE,ADRESSE,NUMERO,RIB,NOM,PRODUIT,DATE_AJOUT) values ('aaaa3',null,'0','0','abcd','gel','01/01/2000');
Insert into HACHEM.FOURNISSEUR (MATRICULE,ADRESSE,NUMERO,RIB,NOM,PRODUIT,DATE_AJOUT) values ('aaa123',null,'0','0','test','gel','01/01/2000');
Insert into HACHEM.FOURNISSEUR (MATRICULE,ADRESSE,NUMERO,RIB,NOM,PRODUIT,DATE_AJOUT) values ('azer',null,'0','0','ttest','gel','01/01/2000');
Insert into HACHEM.FOURNISSEUR (MATRICULE,ADRESSE,NUMERO,RIB,NOM,PRODUIT,DATE_AJOUT) values ('545',null,'0','0','nomlo','gel','01/01/2000');
REM INSERTING into HACHEM.LIVRAISON
SET DEFINE OFF;
Insert into HACHEM.LIVRAISON (NUM_COM,PRODUIT,QUANTITE,LIVREUR,TOTAL,DATE_ARRIVEE) values ('5626457','azestdr','9854','qzwxertf','584','qesrghjg');
Insert into HACHEM.LIVRAISON (NUM_COM,PRODUIT,QUANTITE,LIVREUR,TOTAL,DATE_ARRIVEE) values ('10000','SAVON','0','fghjkl','0','2/1/2021');
Insert into HACHEM.LIVRAISON (NUM_COM,PRODUIT,QUANTITE,LIVREUR,TOTAL,DATE_ARRIVEE) values ('0',null,'0',null,'0',null);
Insert into HACHEM.LIVRAISON (NUM_COM,PRODUIT,QUANTITE,LIVREUR,TOTAL,DATE_ARRIVEE) values ('5','shampooing','456','Zied','125478','12/01/2020');
Insert into HACHEM.LIVRAISON (NUM_COM,PRODUIT,QUANTITE,LIVREUR,TOTAL,DATE_ARRIVEE) values ('45','savon','48','bvnc,;x','785412','2/6/2021');
REM INSERTING into HACHEM.MACHINE
SET DEFINE OFF;
REM INSERTING into HACHEM.MP
SET DEFINE OFF;
Insert into HACHEM.MP (REFERENCE,DESCRIPTION,EMPLACEMENT,QUANTITE,PRIX,DATE_ACHAT,POIDS,VOLUME,COMMENTAIRE) values ('57','dsgssd',null,'0','0','01/01/2000','0','0',null);
Insert into HACHEM.MP (REFERENCE,DESCRIPTION,EMPLACEMENT,QUANTITE,PRIX,DATE_ACHAT,POIDS,VOLUME,COMMENTAIRE) values ('2',null,null,'0','0','01/01/2000','0','0',null);
Insert into HACHEM.MP (REFERENCE,DESCRIPTION,EMPLACEMENT,QUANTITE,PRIX,DATE_ACHAT,POIDS,VOLUME,COMMENTAIRE) values ('mah','dfghjk','fdg','10','15','01/01/2000','5','8','rsfdgvb');
Insert into HACHEM.MP (REFERENCE,DESCRIPTION,EMPLACEMENT,QUANTITE,PRIX,DATE_ACHAT,POIDS,VOLUME,COMMENTAIRE) values ('100','dsgssd',null,'0','0','01/01/2000','0','0',null);
Insert into HACHEM.MP (REFERENCE,DESCRIPTION,EMPLACEMENT,QUANTITE,PRIX,DATE_ACHAT,POIDS,VOLUME,COMMENTAIRE) values ('dfsfs','dsgssd',null,'0','0','01/01/2000','0','0',null);
Insert into HACHEM.MP (REFERENCE,DESCRIPTION,EMPLACEMENT,QUANTITE,PRIX,DATE_ACHAT,POIDS,VOLUME,COMMENTAIRE) values ('77',null,null,'0','0','01/01/2000','0','0',null);
Insert into HACHEM.MP (REFERENCE,DESCRIPTION,EMPLACEMENT,QUANTITE,PRIX,DATE_ACHAT,POIDS,VOLUME,COMMENTAIRE) values ('sdcsvs','fdbdf',null,'0','0','01/01/2000','2','0',null);
REM INSERTING into HACHEM.PRODUIT
SET DEFINE OFF;
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values (null,null,'bhjnk','0','01/01/2000','01/01/2000',null,'0','0','0','0',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values (null,null,'7','0','01/01/2000','01/01/2000',null,'0','0','0','0',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values (null,null,'5','0','01/01/2000','01/01/2000',null,'0','0','0','0',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values (null,null,'8','0','01/01/2000','01/01/2000',null,'0','0','0','0',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values ('Hygienne des mains','ccccc','aaaa','0','01/01/2001','01/01/2002',null,'0','0','0','0',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values ('Hygiene du linge','dfgvfdgvfdfd','gdbgfdgb','500','20/01/2000','24/01/2000','sdvfdfd','500','500','500','11',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values (null,null,'mm','0','02/01/2001','01/01/2001',null,'0','0','0','0',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values (null,null,'2','0','01/01/2000','01/01/2000',null,'0','0','0','0',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values (null,null,'6','0','01/01/2000','01/01/2000',null,'0','0','0','0',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values (null,null,'10','0','01/01/2000','01/01/2000',null,'0','0','0','0',null);
Insert into HACHEM.PRODUIT (CATEGORIE,DESCRIPTION,REFERENCE,QUANTITE,DATE_DE_CREATION,DATE_D_EXPIRATION,EMPLACEMENT,PRIX,DIMENSIONS,POIDS,VOLUME,COMMENTAIRE) values (null,null,'dsjfkdss','0','01/01/2000','15/01/2000',null,'0','0','0','0',null);
REM INSERTING into HACHEM.RECLAMATION
SET DEFINE OFF;
REM INSERTING into HACHEM.VENTE
SET DEFINE OFF;
Insert into HACHEM.VENTE (NUM_VENTE,PROD,QUANT,ID,TOT,DATE_ARR) values ('8','Alcool','789','78965478','456123','12/08/2019');
Insert into HACHEM.VENTE (NUM_VENTE,PROD,QUANT,ID,TOT,DATE_ARR) values ('7','Savon','787','78965475','456127','12/08/2020');
--------------------------------------------------------
--  DDL for Index ACHAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."ACHAT_PK" ON "HACHEM"."ACHAT" ("NUM_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CARTEFIDELITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."CARTEFIDELITE_PK" ON "HACHEM"."CARTE_FIDELITE" ("NUM_CARTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."CLIENT_PK" ON "HACHEM"."CLIENT" ("MATRICULE_FISCALE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMPOSITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."COMPOSITION_PK" ON "HACHEM"."COMPOSITION" ("REF_PRODUIT", "REF_MP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."CONGE_PK" ON "HACHEM"."CONGE" ("ID_CONGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."EMPLOYE_PK" ON "HACHEM"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."FOURNISSEUR_PK" ON "HACHEM"."FOURNISSEUR" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIVRAISON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."LIVRAISON_PK" ON "HACHEM"."LIVRAISON" ("NUM_COM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MACHINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."MACHINE_PK" ON "HACHEM"."MACHINE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."MP_PK" ON "HACHEM"."MP" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."PRODUIT_PK" ON "HACHEM"."PRODUIT" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."RECLAMATION_PK1" ON "HACHEM"."RECLAMATION" ("CODEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HACHEM"."VENTE_PK" ON "HACHEM"."VENTE" ("NUM_VENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACHAT
--------------------------------------------------------

  ALTER TABLE "HACHEM"."ACHAT" ADD CONSTRAINT "ACHAT_PK" PRIMARY KEY ("NUM_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."ACHAT" MODIFY ("NUM_COMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARTE_FIDELITE
--------------------------------------------------------

  ALTER TABLE "HACHEM"."CARTE_FIDELITE" ADD CONSTRAINT "CARTEFIDELITE_PK" PRIMARY KEY ("NUM_CARTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."CARTE_FIDELITE" MODIFY ("NUM_CARTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "HACHEM"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("MATRICULE_FISCALE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."CLIENT" MODIFY ("MATRICULE_FISCALE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPOSITION
--------------------------------------------------------

  ALTER TABLE "HACHEM"."COMPOSITION" ADD CONSTRAINT "COMPOSITION_PK" PRIMARY KEY ("REF_PRODUIT", "REF_MP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."COMPOSITION" MODIFY ("REF_PRODUIT" NOT NULL ENABLE);
 
  ALTER TABLE "HACHEM"."COMPOSITION" MODIFY ("REF_MP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "HACHEM"."CONGE" ADD CONSTRAINT "CONGE_PK" PRIMARY KEY ("ID_CONGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."CONGE" MODIFY ("ID_CONGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "HACHEM"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "HACHEM"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."FOURNISSEUR" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIVRAISON
--------------------------------------------------------

  ALTER TABLE "HACHEM"."LIVRAISON" ADD CONSTRAINT "LIVRAISON_PK" PRIMARY KEY ("NUM_COM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."LIVRAISON" MODIFY ("NUM_COM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MACHINE
--------------------------------------------------------

  ALTER TABLE "HACHEM"."MACHINE" ADD CONSTRAINT "MACHINE_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."MACHINE" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MP
--------------------------------------------------------

  ALTER TABLE "HACHEM"."MP" ADD CONSTRAINT "MP_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."MP" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "HACHEM"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."PRODUIT" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "HACHEM"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_PK1" PRIMARY KEY ("CODEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "HACHEM"."RECLAMATION" MODIFY ("CODEM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENTE
--------------------------------------------------------

  ALTER TABLE "HACHEM"."VENTE" MODIFY ("NUM_VENTE" NOT NULL ENABLE);
 
  ALTER TABLE "HACHEM"."VENTE" ADD CONSTRAINT "VENTE_PK" PRIMARY KEY ("NUM_VENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARTE_FIDELITE
--------------------------------------------------------

  ALTER TABLE "HACHEM"."CARTE_FIDELITE" ADD CONSTRAINT "CARTEFIDELITE_FK1" FOREIGN KEY ("MATRICULE_FISCALE")
	  REFERENCES "HACHEM"."CLIENT" ("MATRICULE_FISCALE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPOSITION
--------------------------------------------------------

  ALTER TABLE "HACHEM"."COMPOSITION" ADD CONSTRAINT "COMPOSITION_FK1" FOREIGN KEY ("REF_PRODUIT")
	  REFERENCES "HACHEM"."PRODUIT" ("REFERENCE") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "HACHEM"."COMPOSITION" ADD CONSTRAINT "COMPOSITION_FK2" FOREIGN KEY ("REF_MP")
	  REFERENCES "HACHEM"."MP" ("REFERENCE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "HACHEM"."CONGE" ADD CONSTRAINT "CONGE_FK1" FOREIGN KEY ("ID")
	  REFERENCES "HACHEM"."EMPLOYE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "HACHEM"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_FK1" FOREIGN KEY ("CODEM")
	  REFERENCES "HACHEM"."MACHINE" ("CODE") ENABLE;
